import NavBar from "@/components/NavBar";
import "./globals.css";

export const metadata = {
  title: "Star Wars Battle App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="overflow-y-scroll  w-full h-full min-h-screen bg-gradient-to-r from-gray-500 to-gray-700">
        <NavBar />
        {children}
      </body>
    </html>
  );
}
